axelera-model-format: 1.0.0

name: retinaface-resnet50-widerface-onnx

description: RetinaFace face detection and landmark localization model trained on WiderFace dataset with ResNet50 backbone

pipeline:
  - detections:
      model_name: retinaface-resnet50-widerface-onnx
      input:
          type: image
          color_format: BGR
          imreader_backend: OpenCV
      preprocess:
          - letterbox:
              scaleup: True
              width: 840
              height: 840
          - torch-totensor:
              scale: False
          - linear-scaling: # [0,1]
              mean: 1, 1, 1
              shift: -104, -117, -123
      postprocess:
          - decode-retinaface:
              box_format: xywh
              normalized_coord: True
              max_nms_boxes: 5000
              conf_threshold: 0.2
              nms_iou_threshold: 0.4
              nms_class_agnostic: True
              nms_top_k: 200
              labels: ['face','background']
              label_filter: ['face']
              eval: # overrides for evaluating accuracy
                conf_threshold: 0.02
                nms_iou_threshold: 0.5
                nms_top_k: 750

operators:
  decode-retinaface:
    class: DecodeRetinaface
    class_path: $AXELERA_FRAMEWORK/ax_models/decoders/retinaface.py


models:
  retinaface-resnet50-widerface-onnx:
    class: AxONNXModel
    class_path: $AXELERA_FRAMEWORK/ax_models/base_onnx.py
    weight_path: weights/Retinaface_resnet50_840.onnx
    weight_url: https://d1o2y3tc25j7ge.cloudfront.net/artifacts/model_cards/weights/others/object_detection/Retinaface_resnet50_840.onnx
    weight_md5: 2c3dbe322cd8ca067e5bb561e0850513
    task_category: ObjectDetection
    input_tensor_layout: NCHW
    input_tensor_shape: [1, 3, 840, 840]
    input_color_format: BGR
    num_classes: 1
    dataset: WiderFace
    extra_kwargs:
      RetinaFace:
        cfg:
          min_sizes: [[16, 32], [64, 128], [256, 512]]
          steps: [8, 16, 32]
          variance: [0.1, 0.2]
          clip: False

datasets:
  WiderFace:
    class: WiderFaceDataAdapter
    class_path: $AXELERA_FRAMEWORK/ax_datasets/widerface.py
    data_dir_name: widerface
    labels_path: $AXELERA_FRAMEWORK/ax_datasets/labels/face.names
    repr_imgs_dir_path: $AXELERA_FRAMEWORK/data/coco2017_400_b680128
    repr_imgs_url: https://d1o2y3tc25j7ge.cloudfront.net/artifacts/data/coco/coco2017_repr400.zip
    repr_imgs_md5: b680128512392586e3c86b670886d9fa
    # cal_data: train/label.txt
    val_data: val/label.txt
