axelera-model-format: 1.0.0

name: yolov8n-license-plate

description: YOLOv8n 640x640 (license plate dataset)
# Pretrained weights from https://github.com/Muhammad-Zeerak-Khan/Automatic-License-Plate-Recognition-using-YOLOv8
# Downloaded at 15-Oct-2024, MIT license
# Model exported by Ultralytics CLI: "yolo export model=license_plate_detector.pt format=onnx opset=13"

pipeline:
  - detections:
      model_name: yolov8n-license-plate
      input:
        type: image
      preprocess:
        - letterbox:
            width: 640
            height: 640
            scaleup: True
        - torch-totensor:
      postprocess:
        - decodeyolo:
            box_format: xywh # box format of the model output
            normalized_coord: False
            max_nms_boxes: 30000
            conf_threshold: 0.25
            nms_iou_threshold: 0.45
            nms_class_agnostic: True
            nms_top_k: 300
            use_multi_label: False
            eval: # overrides for evaluating accuracy
              conf_threshold: 0.001
              nms_iou_threshold: 0.65
              use_multi_label: True
              nms_class_agnostic: False

operators:
  decodeyolo:
    class: DecodeYolo
    class_path: $AXELERA_FRAMEWORK/ax_models/decoders/yolo.py


models:
  yolov8n-license-plate:
    class: AxONNXModel
    class_path: $AXELERA_FRAMEWORK/ax_models/base_onnx.py
    task_category: ObjectDetection
    input_tensor_layout: NCHW
    input_tensor_shape: [1, 3, 640, 640]
    input_color_format: RGB
    weight_path: weights/yolov8n_license_plate_detector.onnx
    weight_url: https://d1o2y3tc25j7ge.cloudfront.net/artifacts/weights/yolo/yolov8n_license_plate_detector.onnx
    weight_md5: 80df1cedb4bbaded6cba64d4a48d1ecc
    num_classes: 1
    dataset: CocoDataset-LicensePlate

datasets:
  CocoDataset-LicensePlate:
    class: ObjDataAdaptor
    class_path: $AXELERA_FRAMEWORK/ax_datasets/objdataadapter.py
    data_dir_name: licenseplate_v4_resized640_aug3x-ACCURATE
    # comment out the url if you are using your local dataset
    dataset_url: https://d1o2y3tc25j7ge.cloudfront.net/artifacts/data/licenseplate_v4_resized640_aug3x-ACCURATE.zip
    # dataset_md5: 85a19e378bf699c0e263e79e4c1a4622 # optional to check md5sum
    dataset_drop_dirs: 0
    # tools/list_relative_image_paths.py can be used to generate the following 2 files
    label_type: YOLOv8
    # Support both options: either point to a directory under data_dir_name that contains images and labels subdirectories, or point to a file with a list of image paths.
    cal_data: valid # val.txt
    val_data: test # test.txt
    labels_path: $AXELERA_FRAMEWORK/ax_models/tutorials/yolo/licenseplate.names
