axelera-model-format: 1.0.0

name: yolov8sseg-yolov8lpose

description: Cascade example - yolov8sseg cascaded into yolov8lpose

pipeline:
  - segmentations:
      model_name: yolov8sseg-coco-onnx
      template_path: $AXELERA_FRAMEWORK/pipeline-template/yoloseg-letterbox.yaml
      input:
        type: image
      postprocess:
        - decodeyoloseg:
            max_nms_boxes: 30000
            conf_threshold: 0.25
            nms_iou_threshold: 0.45
            nms_top_k: 300
            unpad: True
  - poses:
      model_name: yolov8lpose-coco-onnx
      input:
        type: image
        source: roi
        where: segmentations
        which: CENTER # AREA, SCORE, CENTER
        top_k: 3
        expand_margin: 0
      preprocess:
        - letterbox:
            width: 640
            height: 640
            scaleup: True
        - torch-totensor:
      postprocess:
        - decodeyolopose:
            box_format: xywh # box format of the model output
            normalized_coord: False
            max_nms_boxes: 30000
            conf_threshold: 0.25
            nms_iou_threshold: 0.45
            nms_top_k: 300

operators:
  decodeyolopose:
    class: DecodeYoloPose
    class_path: $AXELERA_FRAMEWORK/ax_models/decoders/yolopose.py
  decodeyoloseg:
    class: DecodeYoloSeg
    class_path: $AXELERA_FRAMEWORK/ax_models/decoders/yoloseg.py

models:
  yolov8lpose-coco-onnx:
    class: AxONNXModel
    class_path: $AXELERA_FRAMEWORK/ax_models/base_onnx.py
    weight_path: weights/yolov8l-pose-v8.1.onnx
    weight_url: https://d1o2y3tc25j7ge.cloudfront.net/artifacts/model_cards/weights/yolo/keypoint_detection/yolov8l-pose-v8.1.onnx
    weight_md5: 60955674e106f59a14afcfec5d310f43
    task_category: KeypointDetection
    input_tensor_layout: NCHW
    input_tensor_shape: [1, 3, 640, 640]
    input_color_format: RGB
    num_classes: 1
    dataset: CocoDataset-COCO2017
    extra_kwargs:
      aipu_cores: 2
  yolov8sseg-coco-onnx:
    class: AxONNXModel
    class_path: $AXELERA_FRAMEWORK/ax_models/base_onnx.py
    weight_path: weights/yolov8s-seg-v8.2.onnx
    weight_url: https://d1o2y3tc25j7ge.cloudfront.net/artifacts/model_cards/weights/yolo/instance_segmentation/yolov8s-seg-v8.2.onnx
    weight_md5: f773576dba47b14b9ed2b86ea3c3a00f
    task_category: InstanceSegmentation
    input_tensor_layout: NCHW
    input_tensor_shape: [1, 3, 640, 640]
    input_color_format: RGB
    num_classes: 80
    dataset: CocoDataset-COCO2017
    extra_kwargs:
      aipu_cores: 2

datasets: # Python dataloader
  CocoDataset-COCO2017:
    class: ObjDataAdaptor
    class_path: $AXELERA_FRAMEWORK/ax_datasets/objdataadapter.py
    data_dir_name: coco
    labels_path: $AXELERA_FRAMEWORK/ax_datasets/labels/coco.names
    download_year: 2017
    repr_imgs_dir_path: $AXELERA_FRAMEWORK/data/coco2017_400_b680128
    repr_imgs_url: https://d1o2y3tc25j7ge.cloudfront.net/artifacts/data/coco/coco2017_repr400.zip
    repr_imgs_md5: b680128512392586e3c86b670886d9fa
