axelera-model-format: 1.0.0

name: yolo26mpose-coco-onnx

description: yolo26m pose estimation, 640x640 (COCO), NMS free model

pipeline:
  - keypoint_detections:
      model_name: yolo26mpose-coco-onnx
      input:
        type: image
      preprocess:
        - letterbox:
            height: ${{input_height}}
            scaleup: true
            width: ${{input_width}}
        - torch-totensor:
      inference:
        handle_all: false
      postprocess:
        - decodeyolopose:
            box_format: xyxy
            conf_threshold: 0.25
            dfl_size: 1
            nms_free: true
            nms_top_k: 300
            normalized_coord: false
            eval:
              conf_threshold: 0.001

models:
  yolo26mpose-coco-onnx:
    class: AxONNXModel
    class_path: $AXELERA_FRAMEWORK/ax_models/base_onnx.py
    weight_path: yolo26m-pose.onnx
    weight_url: https://media.axelera.ai/artifacts/model_cards/weights/yolo/keypoint_detection/yolo26m-pose-202602-official.onnx
    weight_md5: 504ad7de27024ac53a84a7ecbdf2bd47
    task_category: KeypointDetection
    input_tensor_layout: NCHW
    input_tensor_shape: [1, 3, 640, 640]
    input_color_format: RGB
    num_classes: 1
    dataset: CocoDataset-keypoint-COCO2017
    extra_kwargs:
      compiler_config_file: yolo26.toml

datasets:
  CocoDataset-keypoint-COCO2017:
    class: KptDataAdapter
    class_path: $AXELERA_FRAMEWORK/ax_datasets/objdataadapter.py
    data_dir_name: coco
    label_type: COCO2017

operators:
  decodeyolopose:
    class: DecodeYoloPose
    class_path: $AXELERA_FRAMEWORK/ax_models/decoders/yolopose.py
