axelera-model-format: 1.0.0

name: yolov5m-tracker-resnet50

description: YOLOv5m-v7.0 with object tracking (OC-SORT) and ResNet50-ImageNet1K

pipeline:
  - master_detections:
      model_name: yolov5m
      template_path: $AXELERA_FRAMEWORK/pipeline-template/yolo-letterbox.yaml
      postprocess:
        - decodeyolo:
            max_nms_boxes: 30000
            conf_threshold: 0.3
            nms_iou_threshold: 0.5
            nms_class_agnostic: False
            nms_top_k: 300
            use_multi_label: False
        - filterdetections:
            min_width: 10
            min_height: 10
        - tracker:
            algorithm: oc-sort
            history_length: 1
            num_subtask_runs: 1
            algo_params:
              max_age: 50
              min_hits: 1
              iou_threshold: 0.25
              # max_id>0 to enable class-based ID management. Each class is
              # expected to have no more than max_id objects at a time. For
              # benchmarking, please set max_id=0
              max_id: 0
  - classifications:
      model_name: ResNet50-ImageNet1K
      input:
        type: image
        source: roi
        where: master_detections
        which: NONE # AREA, SCORE, CENTER
        top_k: 10
        expand_margin: 0
      preprocess:
        - resize:
            size: 256
        - centercrop:
            width: 224
            height: 224
        - torch-totensor:
        - normalize:
            mean: 0.485, 0.456, 0.406
            std: 0.229, 0.224, 0.225
      postprocess:
        - topk:
            k: 1
        - addclassificationstotracker:
            where: master_detections

models:
  yolov5m:
    class: AxONNXModel
    class_path: $AXELERA_FRAMEWORK/ax_models/base_onnx.py
    weight_path: weights/yolov5m-v7.onnx
    weight_url: https://d1o2y3tc25j7ge.cloudfront.net/artifacts/weights/yolo/op17/yolov5m-v7.onnx
    weight_md5: aad63caa41a389d409717a0bbaa17311
    task_category: ObjectDetection
    input_tensor_layout: NCHW
    input_tensor_shape: [1, 3, 640, 640]
    input_color_format: RGB
    num_classes: 80
    dataset: CocoDataset-COCO2017
    extra_kwargs:
      aipu_cores: 3
      YOLO:
        anchors: # or, specified explicitly
        - [10,13, 16,30, 33,23]
        - [30,61, 62,45, 59,119]
        - [116,90, 156,198, 373,326]
        strides: [8, 16, 32]  # specify if you are using a special version
  ResNet50-ImageNet1K:
    class: AxTorchvisionResNet
    class_path: $AXELERA_FRAMEWORK/ax_models/torchvision/resnet.py
    task_category: Classification
    input_tensor_layout: NCHW
    input_tensor_shape: [1, 3, 224, 224]
    input_color_format: RGB # RGB, BGR, Gray
    dataset: ImageNet-1K
    num_classes: 1000
    extra_kwargs:
      max_compiler_cores: 4
      aipu_cores: 1
      compilation_config:
        backend_config:
          single_op_network_use_ddr: True
          single_op_network_aicore_start_idx: 3
      torchvision_args:
        block: Bottleneck
        layers: [3, 4, 6, 3]
        torchvision_weights_args:
          object: ResNet50_Weights
          name: IMAGENET1K_V1

datasets: # Python dataloader
  CocoDataset-COCO2017:
    class: ObjDataAdaptor
    class_path: $AXELERA_FRAMEWORK/ax_datasets/objdataadapter.py
    data_dir_name: coco
    labels_path: $AXELERA_FRAMEWORK/ax_datasets/labels/coco.names
    download_year: 2017
    repr_imgs_dir_path: $AXELERA_FRAMEWORK/data/coco2017_400_b680128
    repr_imgs_url: https://d1o2y3tc25j7ge.cloudfront.net/artifacts/data/coco/coco2017_repr400.zip
    repr_imgs_md5: b680128512392586e3c86b670886d9fa
  ImageNet-1K:
    class: TorchvisionDataAdapter
    class_path: $AXELERA_FRAMEWORK/ax_datasets/torchvision.py
    data_dir_name: ImageNet
    labels_path: $AXELERA_FRAMEWORK/ax_datasets/labels/imagenet1000_clsidx_to_labels.txt
    repr_imgs_dir_path: $AXELERA_FRAMEWORK/data/coco2017_400_b680128
    repr_imgs_url: https://d1o2y3tc25j7ge.cloudfront.net/artifacts/data/coco/coco2017_repr400.zip
    repr_imgs_md5: b680128512392586e3c86b670886d9fa
