axelera-model-format: 1.0.0

name: efficientnet_b1-imagenet

description: EfficientNet_B1 (ImageNet) - v1.5 from torchvision

pipeline:
  - efficientnet_b1-imagenet:
      template_path: $AXELERA_FRAMEWORK/pipeline-template/torch-imagenet.yaml
      postprocess:
        - topk:
            k: 5

models:
  efficientnet_b1-imagenet:
    class: AxTorchvisionEfficientNet
    class_path: $AXELERA_FRAMEWORK/ax_models/torchvision/efficientnet.py
    task_category: Classification
    input_tensor_layout: NCHW
    input_tensor_shape: [1, 3, 224, 224]
    input_color_format: RGB
    dataset: ImageNet-1K
    num_classes: 1000
    extra_kwargs:
      torchvision_args:
        torchvision_weights_args:
          object: EfficientNet_B1_Weights
          name: IMAGENET1K_V1
      compilation_config:
        backend_config:
          in_core_replication: False
        quantization_config:
          ptq_scheme: hybrid_per_tensor_per_channel


datasets:
  ImageNet-1K:
    class: TorchvisionDataAdapter
    class_path: $AXELERA_FRAMEWORK/ax_datasets/torchvision.py
    data_dir_name: ImageNet
    labels_path: $AXELERA_FRAMEWORK/ax_datasets/labels/imagenet1000_clsidx_to_labels.txt
    # Use COCO as representative images due to ImageNet's redistribution restrictions and large dataset size.
    # Suggest selecting 100-400 images from the ImageNet training dataset for representative images and
    # replacing the following representative_coco dataset with the selected images.
    repr_imgs_dir_path: $AXELERA_FRAMEWORK/data/coco2017_400_b680128
    repr_imgs_url: https://d1o2y3tc25j7ge.cloudfront.net/artifacts/data/coco/coco2017_repr400.zip
    repr_imgs_md5: b680128512392586e3c86b670886d9fa
    # cal_data: /path/to/the/cal/dir
    # val_data: /path/to/the/val/dir
