# Copyright Axelera AI, 2026
# ------------------------------------------------------------------------------
# GENERATED by axzoo build from classification/resnet50_imagenet.py
# Backend:     axrelay
#
# IN-REPO (committed under model_recipes/): do NOT hand-edit -- CI drift-check
#   rejects edits; run `axzoo drift-check --fix` to refresh after a config change.
# FORKED  (copied out via `axzoo fork --script`): free to edit; run with
#   `python resnet50_imagenet_axrelay.py`.
# ------------------------------------------------------------------------------
from __future__ import annotations

import json
import os
import shutil
import tempfile
from pathlib import Path

from axelera.runtime2 import op
from axelera.zoo._logging import configure_logging
from axelera.zoo.build.bake import (
    build_calibration_iterator,
    locate_axm,
    check_compat,
    resolve_asset,
    resolve_calibration_dataset,
)
from axelera.zoo.interfaces import RepresentativeImagesRef, LocalImagesRef

# Quiet compiler + third-party log noise; `axzoo build -v` (AXZOO_VERBOSE=1) restores it.
configure_logging(verbosity=1 if os.environ.get('AXZOO_VERBOSE') == '1' else 0)

# Warn (never crash) when this script predates the installed zoo.
check_compat(
    backend='axrelay',
    fingerprint='1.0.0',
    bake_api_version=2,
)

# === Inputs resolved from BuildConfig ===
INPUT_SIZE = [1, 3, 224, 224]
NUM_CAL = 100
MODEL_NAME = 'resnet50-imagenet'
# `axzoo build` sets AXZOO_OUTPUT; a standalone run writes here.
OUTPUT_PATH = Path(os.environ.get('AXZOO_OUTPUT', 'build/resnet50-imagenet.axm'))
MODEL_METADATA = json.loads(os.environ.get('AXZOO_METADATA_JSON', '{}'))

# === Weight-format sources ===
# Each declared source is embedded; AXZOO_WEIGHT_FORMAT picks one at build
# time (default: DEFAULT_WEIGHT_FORMAT).
DEFAULT_WEIGHT_FORMAT = 'onnx'
SOURCES = {
    'onnx': {
        'kind': 'remote',
        'weight_url': 'weights/classification/resnet50_pretrained.onnx',
        'weight_path': 'resnet50_pretrained.onnx',
        'md5': '1d3fb2a01c64125ded6e8e4a164cdd15',
    }
}
WEIGHT_FORMAT = os.environ.get('AXZOO_WEIGHT_FORMAT') or DEFAULT_WEIGHT_FORMAT
if WEIGHT_FORMAT not in SOURCES:
    _avail = ', '.join(sorted(SOURCES))
    raise SystemExit(
        f'AXZOO_WEIGHT_FORMAT={WEIGHT_FORMAT!r} is not an embedded source for this '
        f'build; choose one of: {_avail}.'
    )
_ACTIVE_SOURCE = SOURCES[WEIGHT_FORMAT]
SOURCE_KIND = Path(_ACTIVE_SOURCE['weight_path']).suffix

# === Preprocess ===
# Must match the runtime pipeline's preprocess exactly: calibration runs
# through the same ops the deployed model sees.
preprocess = op.seq(
    op.color_convert(dst='RGB'),
    op.resize(size=256),
    op.center_crop(size=(224, 224)),
    op.to_tensor(),
    op.normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
)


# === Pipeline (production, end-to-end) ===
# The exact pipeline this model runs: preprocess -> the compiled .axm -> postprocess.
def build_pipeline(axm_path):
    return op.seq(
        preprocess,
        op.load(str(axm_path)),
        op.Softmax(),
        op.TopK(k=5),
        op.Unpack(),
        op.AxClassification(class_id_type=op.ImagenetClasses),
    )


# === Calibration source ===
# Active key: 'repr'.
CALIBRATION = RepresentativeImagesRef(
    url='https://media.axelera.ai/artifacts/data/coco/coco2017_repr416.zip',
    path='coco2017_repr400',
    md5='a923038acd372907e8b4b811e6c069bc',
)

# --- use your own model: change exactly two declarations -----------------
# 1. point load_source() at your exported file:
#        return Path('/path/to/your_model.onnx')
# 2. calibrate on ~200 images representative of your deployment scene:
#        CALIBRATION = LocalImagesRef(path='/path/to/your_images/')
# Edit `preprocess` above to match your model's preprocessing, then run
# `python resnet50_imagenet_axrelay.py`.
# ------------------------------------------------------------------------------

_ = LocalImagesRef  # kept for the own-model edit above


def load_source() -> Path:
    return resolve_asset(
        weight_url=_ACTIVE_SOURCE['weight_url'],
        weight_path=_ACTIVE_SOURCE['weight_path'],
        md5=_ACTIVE_SOURCE['md5'],
    )


TASK = 'classification'


def main() -> None:
    import torch
    from axelera import compiler
    from axelera.compiler import CompilerConfig

    print('[stage] load_source')
    source_path = load_source()
    # axelera.compiler.quantize accepts `Union[torch.nn.Module,
    # onnx.ModelProto, str]`. We pass either the .onnx path string
    # or the torch.export-recovered nn.Module.
    if source_path.suffix == '.onnx':
        model_input = str(source_path.resolve())
    elif source_path.suffix == '.pt2':
        model_input = torch.export.load(str(source_path)).module()
    else:
        raise NotImplementedError(
            f'Axrelay cell cannot ingest {source_path.suffix!r} sources. '
            f'Supported: .onnx, .pt2.'
        )

    print('[stage] prepare_calibration')
    cal_dataset = resolve_calibration_dataset(CALIBRATION)
    cal_iter = build_calibration_iterator(
        preprocess=preprocess,
        dataset=cal_dataset,
        num_samples=NUM_CAL,
    )

    print('[stage] compile_to_axm')
    with tempfile.TemporaryDirectory(prefix='axzoo-axrelay-') as tmp_dir:
        tmp_root = Path(tmp_dir)
        compiler_cfg = CompilerConfig(
            output_axm_format=True,
            model_name=MODEL_NAME,
            output_dir=tmp_root / 'build' / MODEL_NAME,
            model_metadata=MODEL_METADATA,
        )
        qmodel = compiler.quantize(
            model=model_input,
            config=compiler_cfg,
            calibration_dataset=cal_iter,
        )
        compiler.compile(qmodel, compiler_cfg, tmp_root / 'build' / MODEL_NAME)

        # axelera.compiler.compile writes <model_name>.axm under tmp_root.
        axm = locate_axm(tmp_root)
        OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(axm, OUTPUT_PATH)
    print(f'[axm] {OUTPUT_PATH}')


if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser(description='Build, then optionally run, this model.')
    parser.add_argument(
        '--run',
        metavar='INPUT',
        help='after building, run end-to-end inference on an image or video; print results',
    )
    parser.add_argument(
        '--benchmark',
        metavar='INPUT',
        help='after building, benchmark the pipeline over an image or video; print fps/latency',
    )
    parser.add_argument(
        '--optimize',
        choices=('auto', 'none'),
        default='auto',
        help='preprocess fusion policy: auto (default; the shipped fused pipeline) '
        'or none to run the raw op sequence for an A/B baseline',
    )
    args = parser.parse_args()
    main()
    if args.run:
        from axelera.zoo.run import iter_results, format_results

        pipeline = build_pipeline(OUTPUT_PATH).optimized(args.optimize)
        for results in iter_results(pipeline, args.run):
            print(format_results(results, task=TASK))
    if args.benchmark:
        from axelera.zoo.bench import benchmark_pipeline, format_benchmark

        pipeline = build_pipeline(OUTPUT_PATH).optimized(args.optimize)
        print(format_benchmark(benchmark_pipeline(pipeline, args.benchmark)))
